#!/usr/bin/env bash

cd $HOME/tools/bin

sed -i '/is_git_repo()/, /is_git_repo/d' git-alias
sed -i '/is_git_repo()/, /is_git_repo/d' git-extras
sed -i '/is_git_repo()/, /is_git_repo/d' git-fork
sed -i '/is_git_repo()/, /is_git_repo/d' git-setup

cd
