#!/usr/bin/env bash

EXTRAS_PATH=$HOME/src/extras
TARGET=$HOME/tools

cd $EXTRAS_PATH
git pull

sed -i '/GIT_EDITOR/d' bin/git-changelog
sed -i '/bash_completion/d' Makefile

make PREFIX=$TARGET install

git checkout master -f

cd

cd $TARGET/bin

sed -i '/is_git_repo()/, /is_git_repo/d' git-alias
sed -i '/is_git_repo()/, /is_git_repo/d' git-extras
sed -i '/is_git_repo()/, /is_git_repo/d' git-fork
sed -i '/is_git_repo()/, /is_git_repo/d' git-setup

cd
