#!/usr/bin/env bash

GIT_PATH=$HOME/src/git
TARGET=$HOME/tools

cd $GIT_PATH

git clean -xdf

git co master -f

git pull

autoreconf -f -v -i

./configure --prefix=$TARGET \
    --without-tcltk \
    --with-libpcre \
    --with-editor=vim

make -j8 all man

make install install-man

cd
