#!/usr/bin/env bash

VIM_PATH=$HOME/src/vim
TARGET=$HOME/tools

cd $VIM_PATH

git clean -xdf
git co master -f
git pull

CC=clang ./configure --prefix=$TARGET \
    --enable-pythoninterp=yes \
    --enable-luainterp=yes \
    --enable-rubyinterp=yes \
    --enable-tclinterp \
    --enable-perlinterp=yes \
    --enable-multibyte \
    --enable-sniff \
    --disable-netbeans \
    --with-features=huge \
    --with-compiledby="gisphm <phmfk@hotmail.com>" \
    --without-x \
    --disable-gui \
    --disable-gpm \
    --enable-fail-if-missing
    # --with-x \
    # --enable-gui=gtk2 \
    # --enable-gpm \

VIMRUNTIMEDIR=$HOME/tools/share/vim/vim74 make -j8

mkdir -p $HOME/tools/share/icons/locolor/32x32/apps
mkdir -p $HOME/tools/share/icons/hicolor/48x48/apps
mkdir -p $HOME/tools/share/icons/locolor/16x16/apps

make install

cd
